### ISSUE TITLE
Incorrect response for SOA request of Alfis zone

### ISSUE THREAD

**Issue by r4sas** [Revertron/Alfis#40] opened 2021-04-14 21:05 UTC
```
# dig SOA ygg @318:1a0f:f6fd:77c::53
;; Got bad packet: FORMERR
84 bytes
75 33 85 83 00 01 00 00 00 01 00 00 03 79 67 67          u3...........ygg
00 00 06 00 01 00 00 00 06 00 01 00 00 00 00 00          ................
33 03 6e 73 30 07 6f 70 65 6e 6e 69 63 04 67 6c          3.ns0.opennic.gl
75 65 00 0a 68 6f 73 74 6d 61 73 74 65 72 c0 25          ue..hostmaster.%
78 76 a5 0b 00 00 07 08 00 00 03 84 00 09 3a 80          xv............:.
00 00 0e 10                                              ....

```

**Comment by Revertron** [comment] 2021-04-14 21:09
Hm, I think I know what the problem is.

**Comment by r4sas** [comment] 2021-04-14 21:10
Correct response example:
```
# dig SOA org

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> SOA org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38438
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 6, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 529c2169965ad3a132399cd960775a0e286ff1adc57f308c (good)
;; QUESTION SECTION:
;org.                           IN      SOA

;; ANSWER SECTION:
org.                    898     IN      SOA     a0.org.afilias-nst.info. noc.afilias-nst.info. 2014320552 1800 900 604800 86400

;; AUTHORITY SECTION:
org.                    172800  IN      NS      c0.org.afilias-nst.info.
org.                    172800  IN      NS      b0.org.afilias-nst.org.
org.                    172800  IN      NS      b2.org.afilias-nst.org.
org.                    172800  IN      NS      d0.org.afilias-nst.org.
org.                    172800  IN      NS      a2.org.afilias-nst.info.
org.                    172800  IN      NS      a0.org.afilias-nst.info.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Apr 14 21:09:34 UTC 2021
;; MSG SIZE  rcvd: 238
```

**Comment by Revertron** [comment] 2021-04-15 10:40
Fixed in https://github.com/Revertron/Alfis/commit/5994622f59a5d71442e404088d92e8ba5369c71a

**Closed by Revertron** 2021-04-15 10:40 UTC
